package br.com.poc.dynamodb.productmanagement;

import java.math.BigDecimal;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Product")
public class Product {
	private String id;
	private String name;
	private String description;
	private Integer stock;
	private BigDecimal price;

	@Deprecated
	public Product() {}

	public Product(String name, String description, Integer stock, BigDecimal price) {
		this.name = name;
		this.description = description;
		this.stock = stock;
		this.price = price;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return this.id;
	}

	@DynamoDBAttribute
	public String getName() {
		return this.name;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return this.description;
	}

	@DynamoDBAttribute
	public Integer getStock() {
		return this.stock;
	}

	@DynamoDBAttribute
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
